Update barematel log collection details
projectceladon/celadon-documentation pull request #299
Opened 2023-07-11 05:58 UTC by usivarax

updated logcollection steps for baremetal on below file 
boot-civ-bare-metal.rst

2023-07-21 05:21 UTC, prashanth-intel approved these changes

2023-11-10 04:45 UTC, bnkoppad requested changes

2023-11-10 04:45 UTC, bnkoppad commented on source/tutorials/boot-civ-bare-metal.rst
> +	RVP Device's with debug port only will support serial log collection
Device's with debug port only shall support serial log collection

2023-11-10 05:07 UTC, bnkoppad approved these changes

2023-11-10 05:36 UTC, iViggyPrabhu commented on source/tutorials/boot-civ-bare-metal.rst
> +Steps to collect serial logs on RVP's bare metal for debugging boot issues
what is RVP here?

2023-11-10 05:38 UTC, swaroopbalan approved these changes

2023-11-10 06:08 UTC, iViggyPrabhu approved these changes
Looks Good.

2023-11-10 06:08 UTC, merged